services:
  json-server-crud:
    image: clue/json-server
    container_name: json-server-crud
    ports:
      - "3001:80"
    volumes:
      - ./data/buses.json:/data/db.json
    environment:
      JSON_SERVER_PORT: 80
    restart: unless-stopped

  json-server-board:
    image: clue/json-server
    container_name: json-server-board
    ports:
      - "3002:80"
    volumes:
      - ./data/board.json:/data/db.json
    environment:
      JSON_SERVER_PORT: 80
    restart: unless-stopped
